# Generated by Django 5.0.6 on 2024-07-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_firstproductpicture_images_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstproductpicture',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
